name: Build and Deploy via SSH

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Build with Gulp
        run: npm run build  # Make sure this runs your Gulp build

      - name: Deploy via rsync over SSH
        uses: burnett01/rsync-deployments@v1.1.0
        with:
          switches: -avzr --delete
          path: dist/
          remote_path: /opt/docker-stack/sites/xbonell.com/dist/
          remote_host: ${{ secrets.VPS_HOST }}
          remote_user: ${{ secrets.VPS_USER }}
          remote_key: ${{ secrets.VPS_SSH_KEY }}
